palabra=str(input("inserte una palabra: "))
palabra2=len(palabra)
a=palabra. count('a')
e=palabra. count('e')
i=palabra. count('i')
o=palabra. count('o')
u=palabra. count('u')
mc=palabra2*(a+e+i+o+u)
print(f"total de vocales: {mc}")
